language: node_js
node_js:
  - 4
  - 5
  - 6
  - node
git:
  depth: 3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --qq libopencv-dev
after_script:
  - npm run-script coveralls
