language: node_js
node_js:
  - 7
  - node
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - sleep 10
git:
  depth: 3
before_install:
  - npm run-script geoip
after_script:
  - npm run-script coveralls
