app:
    url: http://95.85.19.94/
    port: 8888
    cacheControl: 31557600000
    secret: Secret #This is a stub. 
    anonymousEmailPosftix: foodex.com
    mapStub: http://95.85.19.94/map/minskmap.png
    demon:
        wakeup: 20000
        foodTimeout: 300000
    fb:
        id: 123456789 #This is a stub
        secret: abcd12345efg #This is a stub
        host: graph.facebook.com
        port: 443
    log:
        file: foodex.log
        handleException: true
        level:
            console: debug
            file: info
    static:
        file:
            ext: png
            length: 21
        folder:
            food: /tmp #This is stub. Real folder will be defined in another config file
            map: /tmp #This is stub. Real folder will be defined in another config file
            length: 4

db:
    url: mongodb://localhost/foodex
