app:
    url: http://rando4.me/
    port: 8888
    cacheControl: 31557600000
    secret: Secret #This is a stub. 
    anonymousEmailPosftix: rando4.me
    reportedImageStub: http://rando4.me/image/image-reported-stub.png
    tokenLength: 21
    citiesJson: src/map/cities.json
    limit:
        time: 300000 #5 mins
        images: 10 #10 images per 5 mins
        ban: 10800000 #3 hours
        imageSize: 30mb
    img:
        quality: 85 
        ext: jpg
        folder:
            origin: origin/
            small: small/
            medium: medium/
            large: large/
        size:
            small: 480
            medium: 800
            large: 1200
    demon:
        wakeup: 20000
        pairingTimeout: 300000
    fb:
        id: 123456789 #This is a stub
        secret: abcd12345efg #This is a stub
        host: graph.facebook.com
        port: 443
    google:
        host: www.googleapis.com
        path: /oauth2/v1/userinfo?access_token=
        port: 443
    log:
        folder: logs
        file: rando.log
        handleException: true
        level:
            console: debug
            file: debug 
    static:
        file:
            ext: png
            length: 21
        folder:
            length: 4
            image: image/
            map: map/
            name: static/
db:
    url: mongodb://localhost/rando
