app:
    url: http://rando4.me/
    host: 127.0.0.1 #nodejs should be invisible from internet. Use proxy server, e.g.: nginx.
    port: 8888
    cacheControl: 31557600000
    secret: STUB
    anonymousEmailPosftix: rando4.me
    reportedImageStub: http://s3.amazonaws.com/img.s.rando4me/reported.jpg
    tokenLength: 21
    citiesJson: src/map/cities.json
    limit:
        time: 600000 #10 mins
        images: 10 #10 images per 10 mins
        ban: 10800000 #3 hours
        imageSize: 30mb
    img:
        quality: 85 
        ext: jpg
        folder:
            origin: origin/
            small: small/
            medium: medium/
            large: large/
        size:
            small: 480
            medium: 800
            large: 1200
    demon:
        wakeup: 20000
        pairingTimeout: 300000
    fb:
        id: 123456789 #This is a stub
        secret: abcd12345efg #This is a stub
        host: graph.facebook.com
        port: 443
    google:
        host: www.googleapis.com
        path: /oauth2/v1/userinfo?access_token=
        port: 443
    log:
        folder: logs
        file: rando.log
        handleException: true
        level:
            console: info
            file: info
    static:
        file:
            ext: png
            length: 21
        folder:
            length: 4
            image: image/
            map: map/
            name: static/
    monitor:
        title: Rando 4Me server status
        url: /monitor
    share:
        url: https://rando4.me/s/
    enabledScaners:
        - nude
        - rgbHistogram
        - face
scripts:
    maskPath: scripts/resources/round-mask.png

db:
    url: mongodb://localhost/rando
    name: rando
    host: localhost
    port: 27017
s3:
    key: AccessKeyIdSTUB
    secret: SecretAccessKeySTUB
    bucket:
        share:
            large: share.l.rnd4.me
        img:
            small: img.s.rando4me
            medium: img.m.rando4me
            large: img.l.rando4me
