app:
    port: 8888
    log:
        file: foodex.log
        handleException: true
        level:
            console: debug
            file: info
    static:
        file:
            ext: png
            length: 21
        folder:
            food: /tmp #This is stub. Real folder will be defined in another config file
            map: /tmp #This is stub. Real folder will be defined in another config file
            length: 4

db:
    url: mongodb://localhost/foodex
